name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: yarn

   
    - name : Run Tests
      run: yarn test --coverage
      env:
        CI: true
        
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with: 
        fail_ci_if_error: true  
